name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 检出代码仓库
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    # 安装指定版本的 VitePress 和 Markdown-it MathJax
    - name: Install specific packages
      run: |
        npm install vitepress@1.0.0-rc.31
        npm add -D markdown-it-mathjax3

    # 安装项目依赖
    - name: Install Dependencies
      run: npm ci

    # 检查 docs/.vitepress 目录是否存在（调试用）
    - name: Debug VitePress Directory
      run: ls -R ./docs/.vitepress || echo "No .vitepress directory found"

    # 构建 VitePress 项目
    - name: Build
      run: npm run build

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist
