name: Deploy VitePress Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 检出代码仓库
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    # 安装指定版本的 VitePress 和 其他依赖
    - name: Install specific packages
      run: |
        npm install vitepress@1.0.0-rc.31
        npm add -D markdown-it-mathjax3
        npm install glob gray-matter
        npm install markdown-it-wikilinks
        npm install vitepress-plugin-search

    # 安装项目依赖
    - name: Install Dependencies
      run: npm ci

    # 创建必要的索引文件来避免死链接
    - name: Create index files for directories
      run: |
        mkdir -p ./docs/aniian/ReID
        mkdir -p ./docs/aniian/Read
        mkdir -p ./docs/aniian/Vision\ Transformer
        mkdir -p ./docs/aniian/Data\ Transfer
        
        # 创建索引文件
        echo "# ReID 相关研究\n\n这是ReID相关研究的索引页面。" > ./docs/aniian/ReID/index.md
        echo "# 阅读笔记\n\n这是阅读笔记的索引页面。" > ./docs/aniian/Read/index.md
        echo "# Vision Transformer\n\n这是Vision Transformer相关笔记的索引页面。" > ./docs/aniian/Vision\ Transformer/index.md
        echo "# 数据传输相关\n\n这是数据传输相关笔记的索引页面。" > ./docs/aniian/Data\ Transfer/index.md
        echo "# 最近更新\n\n这里展示最近更新的内容。" > ./docs/recent.md

    # 运行自定义脚本
    - name: Run custom scripts
      run: |
        # 如果脚本存在则运行
        if [ -f "./scripts/process-obsidian.js" ]; then
          node ./scripts/process-obsidian.js
        fi
        if [ -f "./scripts/generate-directory.js" ]; then
          node ./scripts/generate-directory.js
        fi

    # 构建 VitePress 项目（忽略死链接）
    - name: Build
      run: npm run build
      env:
        # 环境变量强制忽略死链接
        VITEPRESS_IGNORE_DEAD_LINKS: true

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist
